### ISSUE TITLE
typeerrorについて

### ISSUE THREAD

**Issue by KITAkeisan** [KCCTdensan/ProCon2017-Solver#11]
list indices must be integers or slices, not tuple
とはどういう意味ですか
pointもlist表示にした方がいいのでしょうか
あとなぜかpointが定義されてないのですがどうしましょう

**Comment by ujiuji54** [comment]
Piece.move()とmainのコード見せてほしい

**Comment by KITAkeisan** [comment]
list = []
		list.append(self._vertexes)
		for vertex in list:
			vertex[0][0] += point[0]
		self._vertexes = list

**Comment by ujiuji54** [comment]
for文の中の
vertex[0][0] += point[0]
でおかしくなってるみたい．
この時のvertexeはタプル型(int, int)だからvertex[0][0]は無いよ．
データの構造がややこしくなってきたらprint()で確認するのがいいと思う！

**Comment by KITAkeisan** [comment]
vertexはタプル型だからリスト型にしたいので空のリストを作りましたが、ほかにどういう方法でリスト型が作成できるのか教えてください

**Comment by ujiuji54** [comment]
変数作ってそこにリスト型のデータを代入すればリスト型になるよ．
vertexをタプルからリストにしてlistに代入するなら
list = [vertex[0], vertex[1]] 
か，list()(taple型からlist型に変換できる)を使って
list = list(vertex)
かな

**Comment by KITAkeisan** [comment]
分かりました、もう一回検討してみます

**Comment by ujiuji54** [comment]
質問したことについて理解できたと思ったら，このissueのcloseお願いします．
