### ISSUE TITLE
配列の計算

### ISSUE THREAD

**Issue by KITAkeisan** [KCCTdensan/ProCon2017-Solver#13]
配列の計算でCのように計算しても、座標の連結しかできません。
座標の計算はnumpyというものをつかわなければなりませんか？
またvertexのx軸表示が
vertex[0][0][0]でしか表示できませんでした。(vertex[0]は要素０番目が出力されるばかりです。)
何か効率の良い方法はありますか。

**Comment by ujiuji54** [comment]
numpy使った方が簡単にできるけど使わなくてもできるよ．
vertexがタプルならvertex[0]でx座標にアクセスできると思うんだけどなぁ…
これもコード見せてもらえるとありがたい．issueにあげてもいいし、自分のブランチにコミットしてプッシュでもok．

**Comment by KITAkeisan** [comment]
list = [self._vertexes]
		listp = [point]
		for vertex in list:
			vertex[0] += listp

		self._vertexes = list	
		point = listp
これですると
TypeError: can only concatenate tuple (not "list") to tuple
がでます

**Comment by ujiuji54** [comment]
pointをリストからタプルにうまく変換できてないから```vertex[0] += listp```で型が合わずにエラーが出てるね．
2行目の
```listp = [point]``` ←listpはpoint(タプル型)が入ったリスト型
を
```listp = list(point)``` ←listpはpoint(リスト型)
にするとできると思う．
この違いを分かって欲しい！

**Comment by KITAkeisan** [comment]
errorでtypeerrorの'tuple' is not callableがでました。試しにprint(callable())
でself._vertexes とpointでやってみましたが、falseと出て先に進めません。
	list = [self._vertexes]
		listp = (point)
		for vertex in list:
			vertex[0] += listp(0)
		
		self._vertexes = list	
		point = listp

**Comment by ujiuji54** [comment]
callable()でTrueが出るのは呼び出し可能な**関数・クラス**．
self._vertexes，pointは変数だからcallable()してもFalseになるよ．
self._vertexes，pointの構造が見たいなら普通にprint()でいいと思う．

**Comment by KITAkeisan** [comment]
TypeError: 'tuple' object is not callable
このエラーの意味は
コードは上記と変わりません

**Comment by TateIsuKanna** [comment]
割り込み失礼します:pensive:

タプルオブジェクトは呼び出せない(関数ではない)．という意味です．
```listp(0)```は```listp```の0番目．という意味ではなく```listp```という関数に0という引数を渡すという意味になります．
実際の所```listp```は関数で無いのでエラーになります．

また，```(point)```は```point```が入ったタプルという意味で，要素が1つのタプルとなるので結局のところ```point```と同じ意味になります．

それと，行番号も含めたエラーも確認したいですし，思わぬ所が原因だったりするので自分のブランチにcommitしてpushして頂いた方がいいと思います．(これが言いたくてコメントしました)

**Comment by KITAkeisan** [comment]
@TateIsuKanna

**Comment by KITAkeisan** [comment]
@TateIsuKanna 　どこにcommitすればいいですか？

**Comment by TateIsuKanna** [comment]
そもそも今どこを実装中か把握していませんが
今実装中なのがPiece.move()関数の続きだったら，そのままPiece.move()ブランチにcommitするか
もしくは，そのブランチを切った(分岐した)ブランチがいいと思います．

**Comment by TateIsuKanna** [comment]
@KITAkeisan テストするソースコードをここに投げて欲しいです．(いずれはユニットテストに組み込みたいですね)

**Comment by KITAkeisan** [comment]
def move(self,point):
		list = (self._vertexes)
		for vertex in list:
			vertex[0] += point[0]
	
		self._vertexes = list	
こんな感じですか？

**Comment by KITAkeisan** [comment]
def move(self,point):
		list = (self._vertexes)
		
		for vertex in list:
こんな感じですか？ 
			vertex[0] += point[0]
		
		self._vertexes = list

**Comment by KITAkeisan** [comment]
def move(self,point):
		list = (self._vertexes)
		
		for vertex in list:
			vertex[0] += point[0]
		
		self._vertexes = list	
		
こんな感じですか？

**Comment by TateIsuKanna** [comment]
@KITAkeisan 
いいえ，実装したソースコードではなくて，動いているか確認するために使ったソースコードです．
テストするための，と言った方が良かったね．

**Comment by KITAkeisan** [comment]
if __name__ == '__main__':

	p1 = Piece.new([(1, 0), (1, 2), (2, 2), (2, 0)])
	p1.move((9,0))
	print(p1.getVertexes())
これですか？

**Comment by TateIsuKanna** [comment]
それです!

35行目の```(self._vertexes)```は上に書いたように```self._vertexes```と書くのと同じです．

タプルはリストに似ていますが，内容を変える事が出来ないという点で異なります．
なので，変更しようとすると次のエラーが出ます．
'tuple' object does not support item assignment
直訳: タプルオブジェクトは項目の割り当てをサポートしません．
意訳: タプルは新しく項目を割り当てられませんよ．

また，```for```の```vertex```はあくまでコピーであり，それを変更しても元の```list```は変更されません．

最早通話した方が分かりやすい気がしてきたw

**Comment by KITAkeisan** [comment]
def move(self,point):
		list1 = list(self._vertexes)
		
		for vertex in range(len(list1)):
			print(list1[vertex][0] + point[0])
			print(list1[vertex][1] + point[1])
　
こんな感じですか？

**Comment by TateIsuKanna** [comment]
## 回答
`point`だけずらした`self._vertexes`のxとyの値をそれぞれ表示する．ならそんな感じです．

`self._vertexes`は既にリストなので`list1 = list(self._vertexes)`としなくてもよいと思います．(可読性のための説明変数なら構いませんけれど)

## (標準モジュールの)上書き
前に`list`と書いてた所が`list1`と書いてるので大丈夫だと思うけど念の為．

ご存知の通り
```python
list((1,2,3))
```
とすることで`(1,2,3)`のタプルから`[1,2,3]`のリストが得られます．
ところが，
```python
list = "何か"
```
などと実行してしまうと，
```python
list((1,2,3))
```
が出来なくなります．`list`がリストを作る機能を失って，ただの文字列`"何か"`になってしまったからです．
これは`list`に限らず`len`など全てで起こります．(対話モードで色々試してみて)

### (余談)もししちゃたらどうするか
```python
from builtins import *
```
説明はまた聞いて下さい．ここに書いても分かりにくいと思うので．

## Markdownでのシンタックスハイライト
3つのバッククォートと言語名かファイル名で囲んだら，シンタックスハイライト効くよ．
\`\`\`python
print("test")
\`\`\`
↓
```python
print("test")
```

ちなみに，あなたが(おそらく意図せず)したように，行頭に4つのスペースを置くと，シンタックスハイライト無しのソースコードを書けます．https://guides.github.com/features/mastering-markdown/
ですが，言語指定無しにバッククォートで囲む方が楽でしょう．
\`\`\`
print("test")
\`\`\`
↓
```
print("test")
```

**Comment by KITAkeisan** [comment]
これって完成でいいんですか？

**Comment by TateIsuKanna** [comment]
表示するだけじゃなくて，変更したら完成だと思いますよ．
(`move()`の動作って`self._vertexes`を`point`だけずらす．であってる?)

**Comment by KITAkeisan** [comment]
def move(self,point):
		
		for vertex in range(len(self._vertexes)):
			self._vertexes[vertex] = (self._vertexes[vertex][0] + point[0],
			self._vertexes[vertex][1] + point[1])
		print(self._vertexes)
これでいいでしょうか？

**Comment by TateIsuKanna** [comment]
お疲れ様です．大丈夫です． 😃 

ちなみに`enumerate`を使うとより簡潔に書けます．https://docs.python.jp/3/library/functions.html#enumerate
```python
for i,vertex in enumerate(self._vertexes):
    self._vertexes[i] = (vertex[0] + point[0], vertex[1] + point[1])
```

commitしてpushして頂けると，こちらはpullするだけで済んで嬉しいです(そちらもコピペするの面倒でしょうし)
間違ってるかもしれなくてもcommitして構いません．(気になるのであればブランチを切ればいいです)

あと，コメントは右上の✏で編集出来ますよ．Previewも活用してみて下さい．

**Comment by KITAkeisan** [comment]
本当にありがとうございます。
